#!/bin/sh

# @licence app begin@
# SPDX-License-Identifier: MPL-2.0
#
# \copyright Copyright (C) 2013-2014, PCA Peugeot Citroen
#
# \file run
#
# \brief This file is part of the Build System.
#
# \author Philippe Colliot <philippe.colliot@mpsa.com>
#
# \version 1.0
#
# This Source Code Form is subject to the terms of the
# Mozilla Public License (MPL), v. 2.0.
# If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# For further information see http://www.genivi.org/.
#
# List of changes:
# 
# <date>, <name>, <description of change>
#
# @licence end@

CURDIR=$PWD

ROOT_DIR=$CURDIR
BIN_DIR=$ROOT_DIR/bin
POI_SERVER_BIN_DIR=$ROOT_DIR/../../src/poi-service/bin
MAIN_DATABASE=poi-database.db
ADDITIONAL_DATABASE=poi-database-additional.db

echo '------------------------start the proof of concept------------------------'

echo 'kill orphan process if necessary'
$CURDIR/kill-all

echo 'run'

if [ ! -f $BIN_DIR/$MAIN_DATABASE ]
then
	echo 'no database available, do ./prepare <name of city> first'
	exit
fi

read language <$BIN_DIR/language.txt
echo $language
cd $BIN_DIR
./poi-contentaccess-module -f $ADDITIONAL_DATABASE -i $language &
cd $POI_SERVER_BIN_DIR
./poi-server -f $BIN_DIR/$MAIN_DATABASE &
cd $BIN_DIR
./poi-client &

