/**
 * Copyright (C) 2013 TomTom International B.V.
 * 
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */
package org.genivi.trafficinfo.tpeg.tpegtables;

/**
 * TPEG Type001
 */
public enum LanguageCode {
  UNKNOWN(0, null, null),
  AFAR(1, "Afar", "aa"),
  ABKHAZIAN(2, "Abkhazian", "ab"),
  AVESTAN(3, "Avestan", "ae"),
  AFRIKAANS(4, "Afrikaans", "af"),
  AKAN(5, "Akan", "ak"),
  AMHARIC(6, "Amharic", "am"),
  ARAGONESE(7, "Aragonese", "an"),
  ARABIC(8, "Arabic", "ar"),
  ASSAMESE(9, "Assamese", "as"),
  AVARIC(10, "Avaric", "av"),
  AYMARA(11, "Aymara", "ay"),
  AZERBAIJANI(12, "Azerbaijani", "az"),
  BASHKIR(13, "Bashkir", "ba"),
  BELARUSIAN(14, "Belarusian", "be"),
  BULGARIAN(15, "Bulgarian", "bg"),
  BIHARI(16, "Bihari", "bh"),
  BISLAMA(17, "Bislama", "bi"),
  BAMBARA(18, "Bambara", "bm"),
  BENGALI(19, "Bengali", "bn"),
  TIBETAN(20, "Tibetan", "bo"),
  BRETON(21, "Breton", "br"),
  BOSNIAN(22, "Bosnian", "bs"),
  CATALAN(23, "Catalan", "ca"),
  CHECHEN(24, "Chechen", "ce"),
  CHAMORRO(25, "Chamorro", "ch"),
  CORSICAN(26, "Corsican", "co"),
  CREE(27, "Cree", "cr"),
  CZECH(28, "Czech", "cs"),
  CHURCH_SLAVIC(29, "Church Slavic", "cu"),
  CHUVASH(30, "Chuvash", "cv"),
  WELSH(31, "Welsh", "cy"),
  DANISH(32, "Danish", "da"),
  GERMAN(33, "German", "de"),
  DIVEHI(34, "Divehi", "dv"),
  DZONGKHA(35, "Dzongkha", "dz"),
  EWE(36, "Ewe", "ee"),
  GREEK(37, "Greek", "el"),
  ENGLISH(38, "English", "en"),
  ESPERANTO(39, "Esperanto", "eo"),
  SPANISH(40, "Spanish", "es"),
  ESTONIAN(41, "Estonian", "et"),
  BASQUE(42, "Basque", "eu"),
  PERSIAN(43, "Persian", "fa"),
  FULAH(44, "Fulah", "ff"),
  FINNISH(45, "Finnish", "fi"),
  FIJIAN(46, "Fijian", "fj"),
  FAROESE(47, "Faroese", "fo"),
  FRENCH(48, "French", "fr"),
  WESTERN_FRISIAN(49, "Western Frisian", "fy"),
  IRISH(50, "Irish", "ga"),
  SCOTTISH_GAELIC(51, "Scottish Gaelic", "gd"),
  GALICIAN(52, "Galician", "gl"),
  GUARANI(53, "Guaraní", "gn"),
  GUJARATI(54, "Gujarati", "gu"),
  MANX(55, "Manx", "gv"),
  HAUSA(56, "Hausa", "ha"),
  HEBREW(57, "Hebrew", "he"),
  HINDI(58, "Hindi", "hi"),
  HIRI(59, "Hiri", "Motu ho"),
  CROATIAN(60, "Croatian", "hr"),
  HAITIAN(61, "Haitian", "ht"),
  HUNGARIAN(62, "Hungarian", "hu"),
  ARMENIAN(63, "Armenian", "hy"),
  HERERO(64, "Herero", "hz"),
  INTERLINGUA(65, "Interlingua", "ia"),
  INDONESIAN(66, "Indonesian", "id"),
  INTERLINGUE(67, "Interlingue", "ie"),
  IGBO(68, "Igbo", "ig"),
  SICHUAN_YI(69, "Sichuan Yi", "ii"),
  INUPIAQ(70, "Inupiaq", "ik"),
  IDO(71, "Ido", "io"),
  ICELANDIC(72, "Icelandic", "is"),
  ITALIAN(73, "Italian", "it"),
  INUKTITUT(74, "Inuktitut", "iu"),
  JAPANESE(75, "Japanese", "ja"),
  JAVANESE(76, "Javanese", "jv"),
  GEORGIAN(77, "Georgian", "ka"),
  KONGO(78, "Kongo", "kg"),
  KIKUYU(79, "Kikuyu", "ki"),
  KUANYAMA(80, "Kuanyama", "kj"),
  KAZAKH(81, "Kazakh", "kk"),
  KALAALLISUT(82, "Kalaallisut", "kl"),
  KHMER(83, "Khmer", "km"),
  KANNADA(84, "Kannada", "kn"),
  KOREAN(85, "Korean", "ko"),
  KANURI(86, "Kanuri", "kr"),
  KASHMIRI(87, "Kashmiri", "ks"),
  KURDISH(88, "Kurdish", "ku"),
  KOMI(89, "Komi", "kv"),
  CORNISH(90, "Cornish", "kw"),
  KIRGHIZ(91, "Kirghiz", "ky"),
  LATIN(92, "Latin", "la"),
  LUXEMBOURGISH(93, "Luxembourgish", "lb"),
  GANDA(94, "Ganda", "lg"),
  LIMBURGISH(95, "Limburgish", "li"),
  LINGALA(96, "Lingala", "ln"),
  LAO(97, "Lao", "lo"),
  LITHUANIAN(98, "Lithuanian", "lt"),
  LUBA_KATANGA(99, "Luba-Katanga", "lu"),
  LATVIAN(100, "Latvian", "lv"),
  MALAGASY(101, "Malagasy", "mg"),
  MARSHALLESE(102, "Marshallese", "mh"),
  MA_ORI(103, "Ma-ori", "mi"),
  MACEDONIAN(104, "Macedonian", "mk /sl"),
  MALAYALAM(105, "Malayalam", "ml"),
  MONGOLIAN(106, "Mongolian", "mn"),
  MOLDAVIAN(107, "Moldavian", "mo"),
  MARATHI(108, "Marathi", "mr"),
  MALAY(109, "Malay", "ms"),
  MALTESE(110, "Maltese", "mt"),
  BURMESE(111, "Burmese", "my"),
  NAURU(112, "Nauru", "na"),
  NORWEGIAN_BOKMAL(113, "Norwegian Bokmål", "nb"),
  NORTH_NDEBELE(114, "North Ndebele", "nd"),
  NAPALI(115, "Nepali", "ne"),
  NDONGA(116, "Ndonga", "ng"),
  DUTCH(117, "Dutch", "nl"),
  NORWEGIAN_NYNORSK(118, "Norwegian Nynorsk", "nn"),
  NORWEGIAN(119, "Norwegian", "no"),
  SOUTH_NDEBELE(120, "South Ndebele", "nr"),
  NAVAJO(121, "Navajo", "nv"),
  CHICHEWA(122, "Chichewa", "ny"),
  OCCITAN(123, "Occitan", "oc"),
  OJIBWA(124, "Ojibwa", "oj"),
  OROMO(125, "Oromo", "om"),
  ORIYA(126, "Oriya", "or"),
  OSSETIAN(127, "Ossetian", "os"),
  PANJABI(128, "Panjabi", "pa"),
  PA_LI(129, "Pa-li", "pi"),
  POLISH(130, "Polish", "pl"),
  PASHTO(131, "Pashto", "ps"),
  PORTUGUESE(132, "Portuguese", "pt"),
  QUECHUA(133, "Quechua", "qu"),
  RAETO_ROMANCE(134, "Raeto-Romance", "rm"),
  KIRUNDI(135, "Kirundi", "rn"),
  ROMANIAN(136, "Romanian", "ro"),
  RUSSIAN(137, "Russian", "ru"),
  KINYARWANDA(138, "Kinyarwanda", "rw"),
  SANSKRIT(139, "Sanskrit", "sa"),
  SARDINIAN(140, "Sardinian", "sc"),
  SINDHI(141, "Sindhi", "sd"),
  NORTHERN_SAMI(142, "Northern Sami", "se"),
  SANGO(143, "Sango", "sg"),
  SERBO_CROATIAN(144, "Serbo-Croatian", "sh"),
  SINHALESE(145, "Sinhalese", "si"),
  SLOVAK(146, "Slovak", "sk"),
  SLOVENIAN(147, "Slovenian", "sl"),
  SAMOAN(148, "Samoan", "sm"),
  SHONA(149, "Shona", "sn"),
  SOMALI(150, "Somali", "so"),
  ALBANIAN(151, "Albanian", "sq"),
  SERBIAN(152, "Serbian", "sr"),
  SWATI(153, "Swati", "ss"),
  SOUTHERN_SOTHO(154, "Southern Sotho", "st"),
  SUNSANESE(155, "Sundanese", "su"),
  SWEDISH(156, "Swedish", "sv"),
  SWAHILI(157, "Swahili", "sw"),
  TAMIL(158, "Tamil", "ta"),
  TELUGU(159, "Telugu", "te"),
  TAJIK(160, "Tajik", "tg"),
  THAI(161, "Thai", "th"),
  TIGRINYA(162, "Tigrinya", "ti"),
  TURKMEN(163, "Turkmen", "tk"),
  TAGALOG(164, "Tagalog", "tl"),
  TSWANA(165, "Tswana", "tn"),
  TONGA(166, "Tonga", "to"),
  TURKISH(167, "Turkish", "tr"),
  TSONGA(168, "Tsonga", "ts"),
  TATAR(169, "Tatar", "tt"),
  TWI(170, "Twi", "tw"),
  TAHITIAN(171, "Tahitian", "ty"),
  UIGHUR(172, "Uighur", "ug"),
  UKRAINIAN(173, "Ukrainian", "uk"),
  URDU(174, "Urdu", "ur"),
  UZBEK(175, "Uzbek", "uz"),
  VENDA(176, "Venda", "ve"),
  VIETNAMESE(177, "Vietnamese", "vi"),
  VOLAPUK(178, "Volapük", "vo"),
  WALLOON(179, "Walloon", "wa"),
  WOLOF(180, "Wolof", "wo"),
  XHOSA(181, "Xhosa", "xh"),
  YIDDISH(182, "Yiddish", "yi"),
  YORUBA(183, "Yoruba", "yo"),
  ZHUANG(184, "Zhuang", "za"),
  CHINESE(185, "Chinese", "zh"),
  ZULU(186, "Zulu", "zu  ");
  
  private int code;
  private String languageName; // TISA-English language name
  private String alpha2Code;   // 2-alpha code of ISO 639
  
  
  private LanguageCode(int code, String languageName, String alpha2Code) {
    this.code = code;
    this.languageName = languageName;
    this.alpha2Code = alpha2Code;
  }

  public int getCode() {
    return code;
  }

  public String getLanguageName() {
    return languageName;
  }

  public String getAlpha2Code() {
    return alpha2Code;
  }

}
