<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="locref" nsURI="http://org.genivi.locref" nsPrefix="locref">
  <eAnnotations source="GenModel">
    <details key="documentation" value="Copyright (C) 2013 TomTom International B.V.&#xD;&#xA;&#xD;&#xA;This Source Code Form is subject to the terms of the Mozilla Public&#xD;&#xA;License, v. 2.0. If a copy of the MPL was not distributed with this&#xD;&#xA;file, You can obtain one at http://mozilla.org/MPL/2.0/."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="LocationReference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="data" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="locationReferenceType"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"
        unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocationReferenceDecodingService">
    <eOperations name="decode">
      <eParameters name="listener" lowerBound="1" eType="#//LocationReferenceDecodingServiceListener"/>
      <eParameters name="locationReference" lowerBound="1" eType="#//LocationReference"/>
    </eOperations>
    <eOperations name="setLanguage">
      <eParameters name="languageCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="countryCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getLanguage">
      <eParameters name="listener" eType="#//LocationReferenceDecodingServiceListener"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocationReferenceDecodingServiceListener">
    <eOperations name="decodeReply">
      <eParameters name="location" lowerBound="1" eType="ecore:EClass ../../org.genivi.basetypes-model/model/Basetypes.ecore#//location/Location"/>
      <eParameters name="locationInfo" eType="ecore:EClass ../../org.genivi.basetypes-model/model/Basetypes.ecore#//location/LocationInfo"/>
    </eOperations>
    <eOperations name="getLanguageReply">
      <eParameters name="languageCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="countryCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LocationReferenceType">
    <eLiterals name="TMC_LOC" value="1"/>
    <eLiterals name="OPEN_LR" value="2"/>
  </eClassifiers>
</ecore:EPackage>
