/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 2.1.6.v20140519.
* Used org.franca.core 0.8.11.201401091023.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
/**
 * This interface offers methods that implement the POI search functionality of a
 *  navigation system.
 */
#ifndef ORG_GENIVI_NAVIGATION_POISERVICE_POI_Content_Manager_H_
#define ORG_GENIVI_NAVIGATION_POISERVICE_POI_Content_Manager_H_




#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/types.h>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace org {
namespace genivi {
namespace navigation {
namespace poiservice {

class POIContentManager {
 public:
    virtual ~POIContentManager() { }

    static inline const char* getInterfaceId();
    static inline CommonAPI::Version getInterfaceVersion();
};

const char* POIContentManager::getInterfaceId() {
    static const char* interfaceId = "org.genivi.navigation.poiservice.POIContentManager";
    return interfaceId;
}

CommonAPI::Version POIContentManager::getInterfaceVersion() {
    return CommonAPI::Version(1, 0);
}


} // namespace poiservice
} // namespace navigation
} // namespace genivi
} // namespace org

namespace CommonAPI {

}


namespace std {
    //hashes for types

    //hashes for error types
}

#endif // ORG_GENIVI_NAVIGATION_POISERVICE_POI_Content_Manager_H_
