#!/bin/bash

./test-location-input.py -l location_tokyo.xml
sleep 2
./test-route-calculation.py -r route_tokyo.xml
sleep 2
./test-address-input.py -l location_tokyo.xml
sleep 2
./test-guidance.py -r route_tokyo.xml
sleep 2
./test-map-viewer-control.py -l location_tokyo.xml
