#!/bin/bash

./test-location-input-capi.py -l locations.xml
sleep 2
./test-route-calculation-capi.py -r routes.xml
sleep 2
./test-address-input-capi.py -l location.xml
sleep 2
./test-guidance-capi.py -r route.xml
sleep 2
./test-map-viewer-control-capi.py

