#! /bin/bash
# @licence app begin@
# SPDX-License-Identifier: MPL-2.0
#
# \copyright Copyright (C) 2013-2014, PCA Peugeot Citroen
#
# \file run
#
# \brief This file is part of the Build System.
#
# \author Martin Schaller <martin.schaller@it-schaller.de>
#
# \version 1.0
#
# This Source Code Form is subject to the terms of the
# Mozilla Public License (MPL), v. 2.0.
# If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# For further information see http://www.genivi.org/.
#
# List of changes:
# 
# 26-6-2014, Marco Residori, Added support of new EnhancedPositionService
#
# @licence end@
function run
{
	local x=$xterm
	local g=$gdb
	local l=$log
	local title="$1"
	shift
	if [ "$1" = "-n" ]
	then
		shift
		x=0
		log=0
	fi
	if [ "$1" = -"g" ]
	then
		shift
		g=0
	fi
	if [ "$x" = 1 ]
	then
		if [ "$g" = 1 ]
		then
			set -- gdb -ex run --args "$@"
		fi
		xterm -T "$title" -sb -sl 5000 -e "$@" &
	elif [ "$log" = 1 ]
	then
		"$@" >"$CUR_DIR/$title.log" 2>&1 &
	else
		"$@" &
	fi
	PIDS="$PIDS $!"
}

function terminate
{
	set +e
	trap "" EXIT INT
	kill $PIDS
}

gdb=0
xterm=0
log=0
enhpos=1
center="4612 N 0608 E"
CUR_DIR=$PWD
BIN_DIR=$PWD/../bin
SRC_DIR=$PWD/..
while getopts b:c:gnox opt
do
	case $opt in
	b)
		BIN_DIR=$OPTARG
		;;
	c)
		case "$OPTARG" in
		paris)
			center="2.34 48.86"
			;;
		tokyo)
			center="139.74 35.70"
			;;
		[0-9-]*)
			center=$OPTARG
			;;
		*)
			echo "Unsupported center $OPTARG" >&2
			exit 1
			;;
		esac
		;;
	g)
		gdb=1
		;;
	n)
		enhpos=0
		;;
	o)
		log=1
		;;
	x)
		xterm=1
		;;
	\?)
		echo "Usage:"
		echo "$0 [-a application][-c center][-lnx]"
		echo "-c: Set center (supported values: paris,tokyo,longitude,latitude). Default is geneve"
		echo "-g: Run subprocesses within gdb (only with -x)"
		echo "-n: Don't start enhanced-position-service"
		echo "-x: Run subprocesses in own xterm to get separated log messages"
		exit 1
	esac
done
trap "terminate" EXIT INT
set -e
if [ "$enhpos" = 1 ]
then
	if [ -z "$REPLAYER_LOG_FILE" ]
	then
		REPLAYER_LOG_FILE=$BIN_DIR/positioning/log-replayer/logs/geneve-cologny.log
	fi
        run LogReplayer $BIN_DIR/positioning/log-replayer/src/log-replayer $REPLAYER_LOG_FILE 
        run EnhancedPositionService $BIN_DIR/positioning/enhanced-position-service/src/enhanced-position-service 
fi
cd $BIN_DIR/navit/navit
>bookmark.txt
echo "$center" >center.txt
run MapViewer ./navit navit_genivi_mapviewer.xml
run NavigationCore ./navit navit_genivi_navigationcore.xml
wait
