#!/bin/sh

# @licence app begin@
# SPDX-License-Identifier: MPL-2.0
#
# \copyright Copyright (C) 2013-2014, PCA Peugeot Citroen
#
# \file run
#
# \brief This file is part of the Build System.
#
# \author Philippe Colliot <philippe.colliot@mpsa.com>
#
# \version 1.0
#
# This Source Code Form is subject to the terms of the
# Mozilla Public License (MPL), v. 2.0.
# If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# For further information see http://www.genivi.org/.
#
# List of changes:
# 
# <date>, <name>, <description of change>
#
# @licence end@

CURDIR=$PWD

ROOT_DIR=$CURDIR
BIN_DIR=$ROOT_DIR/bin
RESOURCE_DIR=$ROOT_DIR/resource
MAIN_DATABASE=$RESOURCE_DIR/poi-database-sample.db
ADDITIONAL_DATABASE=$RESOURCE_DIR/poi-database-managed.db

echo 'kill reminding orphan process if necessary'
./kill-all

echo '------------------------start the server------------------------'
$BIN_DIR/poi-server -f $MAIN_DATABASE &

echo '------------------------start the manager server------------------------'
#$MANAGER_SERVER_EXE_DIR/poi-manager-server -f $ADDITIONAL_DATABASE &



