#!/bin/bash

export PYTHONIOENCODING=utf-8

result="$(./test-location-input.py -l ../resource/locations.xml 2>&1 >/dev/null)"
echo $result
if [[ $result != *"PASSED"* ]]; then 
	exit 1 
fi

result="$(./test-address-input.py -l ../resource/location.xml  2>&1 >/dev/null)"
echo $result
if [[ $result != *"PASSED"* ]]; then 
	exit 1 
fi

result="$(./test-route-calculation.py -r ../resource/routes.xml  2>&1 >/dev/null)"
echo $result
if [[ $result != *"PASSED"* ]]; then 
	exit 1 
fi

result="$(./test-poi.py -l ../resource/location.xml -s "sChü" 2>&1 >/dev/null)"
echo $result
if [[ $result != *"PASSED"* ]]; then 
	exit 1 
fi

result="$(./test-poi-guidance.py -l ../resource/location-poi.xml -s "cOnT" 2>&1 >/dev/null)"
echo $result
if [[ $result != *"PASSED"* ]]; then 
	exit 1 
fi

result="$(./test-guidance.py -r ../resource/route.xml  2>&1 >/dev/null)"
echo $result
if [[ $result != *"PASSED"* ]]; then 
	exit 1 
fi

result="$(./test-map-viewer-control.py -l ../resource/location.xml  2>&1 >/dev/null)"
echo $result
if [[ $result == *"PASSED"* ]]; then 
	echo "Batch test PASSED" 
fi
