#!/bin/bash

./test-location-input.py -l ../resource/location_tokyo.xml
sleep 2
./test-route-calculation.py -r ../resource/route_tokyo.xml
sleep 2
./test-address-input.py -l ../resource/location_tokyo.xml
sleep 2
./test-guidance.py -r ../resource/route_tokyo.xml
sleep 2
./test-map-viewer-control.py -l ../resource/location_tokyo.xml
